### ISSUE TITLE
'That model does not exist' error

### ISSUE THREAD

**Issue by aadarshgupta1412** [robgon-art/ai-tunes#1]
In AI-Tunes Generate Music notebook, I am facing this error as max_tokens = 1000 from the part :

response = openai.Completion.create(
      model="curie:ft-user-j0julqovorjakyuyt3kv3zci-2021-08-24-11-42-59",prompt=prompt,
      stop = " $ <end>",
      temperature=temperature,
      top_p=1.0,
      frequency_penalty=0.0,
      presence_penalty=0.0,
      max_tokens = 64)    <--

**Comment by robgon-art** [comment]
Hello. I took a look at this and the problem isn't with the max_tokens. 

But there is a problem with sharing fine-tuned models. In order to get this to work, you will need to run the [training Colab](https://colab.research.google.com/github/robgon-art/ai-tunes/blob/main/AI_Tunes_GPT_3_Training.ipynb) first, and then copy the name of the fine-tuned model. For example, for me it was 

[2021-10-09 17:13:40] Uploaded model: **curie:ft-user-j0julqovorjakyuyt3kv3zci-2021-08-24-11-42-59**

Next, you have to paste the model name into line 17 of the Generate Songs section of the [song generation Colab](https://colab.research.google.com/github/robgon-art/ai-tunes/blob/main/AI_Tunes_Generate_Music.ipynb).

You can save your changed Colab into your Google Drive for later use.

Please let me know if this works.

Cheers, Rob
